// <auto-generated />
namespace MvcApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class changetelephonenumbertostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetelephonenumbertostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201401031259041_change telephonenumber to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
